name: Cloud Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Use Eclipse Temurin JDK

      - name: Build with Maven
        run: mvn clean package  # Builds the project

      - name: Run Tests
        run: mvn test  # Runs unit tests

      - name: Start Java Application
        run: nohup java -jar target/cloud-1.0-SNAPSHOT.jar > app.log 2>&1 &  # Runs in background

      - name: Wait for Service to Start
        run: sleep 10  # Wait for 10 seconds to allow Spring Boot to start

      - name: Check Service Status
        run: curl -s http://localhost:9090/ || (echo "Service is not running!" && cat app.log && exit 1)
